apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devspaces
  namespace: tooling
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  installPlanApproval: Automatic
  startingCSV: devspacesoperator.v3.3.0
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: devspaces