apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-camel-k
  namespace: tooling
spec:
  channel: 1.8.x
  installPlanApproval: Automatic
  startingCSV: red-hat-camel-k-operator.v1.8.1-0.1667495781.p
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: red-hat-camel-k