apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: rhte-artemis
  namespace: tooling
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"    
spec:
  acceptors:
    - name: non-ssl
      port: 5672
      protocols: 'amqp,core'
      expose: true
      sslEnabled: false
      verifyHost: false
    - name: ssl
      port: 5673
      protocols: 'amqp,core'
      sslEnabled: true
      sslSecret: my-tls-secret
      expose: true
      verifyHost: false
      trustStoreType: PKCS12
  deploymentPlan:
    image: placeholder
    size: 1
    requireLogin: true
    persistenceEnabled: false
    journalType: nio
    messageMigration: false
    jolokiaAgentEnabled: false
    managementRBACEnabled: true
  addressSettings:
    addressSetting:
      - autoCreateQueues: true
        autoCreateAddresses: true
  console:
    expose: true
    useClientAuth: true
  adminUser: admin
  adminPassword: password1!
