apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: community-camel-k
  namespace: tooling
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"  
spec:
  channel: stable-1.10
  installPlanApproval: Automatic
  name: camel-k
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: camel-k-operator.v1.10.3