kind: Secret
apiVersion: v1
metadata:
  name: gitlab-oauth-config
  namespace: openshift-operators
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: gitlab
    che.eclipse.org/scm-server-endpoint: https://gitlab.consulting.redhat.com
type: Opaque
data:
  id: M2ViODcxYTU3ODM0NWE4Yzk3MTAyNTU3ZjhhNjEzNmI1MDZkMjc0N2Y2MDI5NjQ5NGIyMjk2ZGQ0MjRjYzNhNA==
  secret: MTFiNTg5MzUwYmU5MDE5NWExMDZlOTc4NzEzNmU4NWU0NDJjNWI1MmIwYzFhMTZmNWM2ZWMwNjliODBmY2NkMg==