apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: devworkspace-gitconfig
objects:  
  - kind: Secret
    apiVersion: v1
    metadata:
      name: workspace-credentials-secret
      namespace: ${USERNAME}-dev
    type: opaque
parameters:
- description: Username
  name: USERNAME              
