apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devspaces
  namespace: tooling
spec:
  channel: stable
  installPlanApproval: Automatic
  startingCSV: devspacesoperator.v3.2.0
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: devspaces