{{- range $key := .Values.users }}
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    che.eclipse.org/plugin-registry-url: https://devspaces.apps.cluster.local:3000/plugin-registry/v3/plugins/eclipse/che-theia/latest/devfile.yaml
  name: {{.name}}-workspace
  namespace: {{.name}}-dev
spec:
  commands:
    - apply:
        component: che-code-injector
      id: init-container-command
  components:
    - name: checode
      volume: {}
    - container:
        cpuRequest: 30m
        command:
          - /entrypoint-init-container.sh
        env:
          - name: CHE_DASHBOARD_URL
            value: https://devspaces.apps.cluster.local:3000
          - name: CHE_PLUGIN_REGISTRY_URL
            value: >-
              https://devspaces.apps.cluster.local:3000/plugin-registry/v3
          - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
            value: http://plugin-registry.openshift-operators.svc:8080/v3
          - name: OPENVSX_REGISTRY_URL
            value: https://open-vsx.org
        memoryRequest: 32Mi
        sourceMapping: /projects
        cpuLimit: 500m
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 128Mi
        image: >-
          registry.redhat.io/devspaces/code-rhel8@sha256:d5efb27645f7ed12d449e8c35f01070b2fb6d247d79c94f374d8781371a17318
      name: che-code-injector
  events:
    preStart:
      - init-container-command
{{- end }}
