{{- range $key := .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.name}}-git-config
  namespace: {{.name}}-dev
  labels:
    controller.devfile.io/git-credential: 'true' 
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-path: ~/.gitconfig 
    rgocd.argoproj.io/sync-wave: "1"    
stringData:
  credentials: "[user]\n  name = {{.name}}\n  email = {{.name}}@example.com \n  password = password"
{{- end }}
