{{- range $key := .Values.users }}
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  annotations:
    che.eclipse.org/components-update-policy: managed
    che.eclipse.org/plugin-registry-url: >-
      # https://devspaces.apps.cluster.local:3000/plugin-registry/v3/plugins/eclipse/che-theia/latest/devfile.yaml
    argocd.argoproj.io/sync-wave: "6"    

  name: {{.name}}-workspace
  namespace: {{.name}}-dev
spec:
  commands:
    - apply:
        component: remote-runtime-injector
      id: init-container-command
  components:
    - name: plugins
      volume: {}
    - name: theia-local
      volume: {}
    - name: remote-endpoint
      volume:
        ephemeral: true
  events:
    preStart:
      - init-container-command
{{- end }}
