spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/agiertli/rhte-camelk
    targetRevision: HEAD
argo:
  namespace: openshift-gitops
  destination: tooling
  project: rhte-camelk-tooling       

applications:
   - name: camelk
   - name: nexus
   - name: amq7
   - name: sealed-secrets/overlays/default