spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/agiertli/rhte-camelk
    targetRevision: HEAD
argo:
  namespace: openshift-gitops
  destination: tooling
  project: rhte-camelk-tooling       

applications:
  #  - name: camelk
  #    path: camelk
   - name: nexus
     path: nexus
   - name: amq7
     path: amq7
   - name: sealed-secrets
     path: sealed-secrets/overlays/default
   - name: namespaces
     path: namespaces  
   - name: gitea
     path: gitea
   - name: camelk-community
     path: camelk-community  
   - name: tekton
     path: tekton  
   - name: devspaces
     path: devspaces  