apiVersion: sonatype.com/v1alpha1
kind: NexusRepo
metadata:
  name: nexus-repository
  namespace: tooling
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  config:
    enabled: false
    mountPath: /sonatype-nexus-conf
  deployment:
    terminationGracePeriodSeconds: 120
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: false
    path: /
    tls:
      enabled: true
      secretName: nexus-tls
  nexus:
    dockerPort: 5003
    env:
    - name: INSTALL4J_ADD_VM_PARAMS
      value: -Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M -XX:+UnlockExperimentalVMOptions
        -XX:+UseCGroupMemoryLimitForHeap
    - name: NEXUS_SECURITY_RANDOMPASSWORD
      value: "false"
    imageName: registry.connect.redhat.com/sonatype/nexus-repository-manager@sha256:0a537bf191cc09fec0787300c7b4de7713afcb00f62774b7a4e5578be6b6ff0e
    imagePullPolicy: IfNotPresent
    imagePullSecret: ""
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    nexusPort: 8081
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    service:
      type: NodePort
  nexusProxyRoute:
    enabled: false
  persistence:
    enabled: false
  replicaCount: 1
  route:
    enabled: false
  secret:
    enabled: false
    mountPath: /etc/secret-volume
    readOnly: true
  service:
    enabled: true
    ports:
    - name: nexus-service
      port: 80
      targetPort: 80
  statefulset:
    enabled: false