apiVersion: batch/v1
kind: Job
metadata:
  name: provision-dev-spaces
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - image: registry.redhat.io/openshift-gitops-1/argocd-rhel8:v1.5.0
        name: provisioner
        command:
          - /bin/bash
          - -c
          - |
            export HOME=/home/argocd
            echo "Checking if this works account already there..."
            git clone -b maz https://github.com/agiertli/rhte-camelk
            cd rhte-camelk/devspaces
            ./createProject.sh
      serviceAccount: openshift-gitops-argocd-application-controller
      serviceAccountName: openshift-gitops-argocd-application-controller
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
