apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-master
spec:
  server:
    insecure: true
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
  rbac:
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
    scopes: '[groups]'      