{{- range $key := .Values.users }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{.name}}-git-config
  namespace: {{.name}}-dev
  labels:
    app.kubernetes.io/defaultName: git-config-secret
    app.kubernetes.io/part-of: devworkspace-operator
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: file
    controller.devfile.io/mount-path: /home/user/.gitconfig 
    argocd.argoproj.io/sync-wave: "-1"    

data:
  gitconfig: |
    [user]
        name = {{.name}}
        email = {{.name}}.che
    [credential]
        helper = store --file /.git-credentials/credentials
{{- end }}
