apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: camelk-instructor-admin
  namespace: camelk-instructor
  annotations:
    argocd.argoproj.io/sync-wave: "1"      
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin

{{- range $key := .Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.name}}-view-camelk-instructor
  namespace: camelk-instructor
  annotations:
    argocd.argoproj.io/sync-wave: "1"      
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{.name}}
{{- end }}  

{{- range $key := .Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: camel-k-pipeline-rb
  namespace: {{.name}}-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"      
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: camel-k-operator
subjects:
- namespace: {{.name}}-dev
  kind: ServiceAccount
  name: camel-k-pipeline-sa
{{- end }}  

{{- range $key := .Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: camel-k-pipeline-rb
  namespace: {{.name}}-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"      
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: camel-k-operator
subjects:
- namespace: {{.name}}-dev
  kind: ServiceAccount
  name: camel-k-pipeline-sa
{{- end }}  